-- Migração dos Cardápios CSV para o Banco de Dados
-- Este script insere todos os cardápios dos arquivos CSV

-- Primeiro, vamos inserir os menus baseados nos arquivos CSV
INSERT INTO menus (name, description, price) VALUES
-- Coffee Break Menus
('COFFEE BREAK PREMIUM', 'Serviço de coffee break premium com opções gourmet', 129.00),
('COFFEE BREAK VIP', 'Serviço de coffee break VIP com opções exclusivas', 89.00),
('COFFEE BREAK STANDARD', 'Serviço de coffee break standard', 69.00),
('COFFEE BREAK BÁSICO', 'Serviço de coffee break básico', 49.00),
('COFFEE BREAK BÁSICO II', 'Serviço de coffee break básico II', 39.00),

-- Café da Manhã Menus
('CAFÉ DA MANHÃ PREMIUM', 'Serviço de café da manhã premium', 89.00),
('CAFÉ DA MANHÃ STANDARD', 'Serviço de café da manhã standard', 59.00),

-- Almoço Menus
('ALMOÇO BUFFET -  PREMIUM', 'Serviço de almoço buffet premium', 249.00),
('ALMOÇO EM BUFFET - VIP', 'Serviço de almoço buffet VIP', 189.00),
('ALMOÇO EM BUFFET – STANDARD', 'Serviço de almoço buffet standard', 149.00),
('ALMOÇO EMPRATADO – 3 TEMPOS', 'Serviço de almoço empratado com 3 tempos', 179.00),

-- Brunch Menu
('BRUNCH', 'Serviço de brunch completo', 129.00),

-- Ilha Gastronômica Menus
('ILHA GASTRONÔMICA VIP', 'Serviço de ilha gastronômica VIP', 299.00),
('ILHA GASTRONÔMICA STANDARD', 'Serviço de ilha gastronômica standard', 199.00),

-- Coquetel Menus
('COQUETEL VOLANTE VIP', 'Serviço de coquetel volante VIP', 159.00),
('COQUETEL VOLANTE STANDARD', 'Serviço de coquetel volante standard', 119.00),
('COQUETEL VOLANTE BÁSICO', 'Serviço de coquetel volante básico', 89.00),

-- Lounge e Lunch Box
('BUFFET LOUNGE HUB', 'Serviço de buffet lounge hub', 139.00),
('LUNCH BOX HUB', 'Serviço de lunch box hub', 99.00)
ON CONFLICT (name) DO NOTHING;

-- Agora vamos inserir os pratos para cada menu
-- COFFEE BREAK PREMIUM
WITH menu AS (SELECT id FROM menus WHERE name = 'COFFEE BREAK PREMIUM')
INSERT INTO dishes (name, description, category, menu_id, price) VALUES
('Água sem Gás', 'Água mineral sem gás', 'BEBIDAS NÃO ALCOÓLICAS', (SELECT id FROM menu), 4.00),
('Café', 'Café 100% arábica', 'BEBIDAS NÃO ALCOÓLICAS', (SELECT id FROM menu), 5.00),
('Leite', 'Leite integral ou desnatado', 'BEBIDAS NÃO ALCOÓLICAS', (SELECT id FROM menu), 4.00),
('Chás Variados', 'Seleção de chás especiais', 'BEBIDAS NÃO ALCOÓLICAS', (SELECT id FROM menu), 5.00),
('Chocolate em Pó', 'Chocolate quente premium', 'BEBIDAS NÃO ALCOÓLICAS', (SELECT id FROM menu), 6.00),
('Iogurte com Granola', 'Iogurte natural com granola artesanal', 'BEBIDAS NÃO ALCOÓLICAS', (SELECT id FROM menu), 7.00),
('2 Sucos', 'Dois sucos naturais da estação', 'BEBIDAS NÃO ALCOÓLICAS', (SELECT id FROM menu), 8.00),
('1 Água Aromatizada', 'Água aromatizada especial', 'BEBIDAS NÃO ALCOÓLICAS', (SELECT id FROM menu), 5.00),
('Limão Siciliano, Hortelã e Manjericão Verde', 'Água aromatizada com limão siciliano', 'ÁGUAS AROMATIZADAS', (SELECT id FROM menu), 6.00),
('Laranja com Manjericão e Mini-Flores', 'Água aromatizada com laranja', 'ÁGUAS AROMATIZADAS', (SELECT id FROM menu), 6.00),
('Alecrim, Limão Taiti e Manjericão Verde', 'Água aromatizada com alecrim', 'ÁGUAS AROMATIZADAS', (SELECT id FROM menu), 6.00),
('Limão com Manjericão Roxo', 'Água aromatizada com manjericão roxo', 'ÁGUAS AROMATIZADAS', (SELECT id FROM menu), 6.00),
('Laranja com Acerola', 'Suco natural de laranja com acerola', 'SUCOS', (SELECT id FROM menu), 7.00),
('Uva com Canela', 'Suco natural de uva com canela', 'SUCOS', (SELECT id FROM menu), 7.00),
('Pink Lemonade', 'Limonada rosa especial', 'SUCOS', (SELECT id FROM menu), 8.00),
('Iced Tea de Pêssego', 'Chá gelado de pêssego', 'SUCOS', (SELECT id FROM menu), 7.00),
('Iced Tea com Limão', 'Chá gelado com limão', 'SUCOS', (SELECT id FROM menu), 7.00),
('Verde Detox', 'Suco verde detox (maçã, limão, gengibre, couve, espinafre, capim santo)', 'SUCOS', (SELECT id FROM menu), 9.00),
('Maracujá com Manjericão', 'Suco de maracujá com manjericão', 'SUCOS', (SELECT id FROM menu), 7.00),
('Laranja com Morango', 'Suco de laranja com morango', 'SUCOS', (SELECT id FROM menu), 7.00),
('Abacaxi com Hortelã', 'Suco de abacaxi com hortelã', 'SUCOS', (SELECT id FROM menu), 7.00),
('Laranja', 'Suco natural de laranja', 'SUCOS', (SELECT id FROM menu), 6.00),
('Abacaxi', 'Suco natural de abacaxi', 'SUCOS', (SELECT id FROM menu), 6.00),
('Uva', 'Suco natural de uva', 'SUCOS', (SELECT id FROM menu), 6.00),
('Limão', 'Suco natural de limão', 'SUCOS', (SELECT id FROM menu), 6.00),
('Esfiha de Queijo', 'Esfiha artesanal de queijo', 'SNACKS', (SELECT id FROM menu), 5.00),
('Esfiha de Ricota', 'Esfiha artesanal de ricota', 'SNACKS', (SELECT id FROM menu), 5.00),
('Esfiha de Carne', 'Esfiha artesanal de carne', 'SNACKS', (SELECT id FROM menu), 6.00),
('Folhado de Calabresa', 'Folhado artesanal de calabresa', 'SNACKS', (SELECT id FROM menu), 6.00),
('Empanadita Argentina de Mussarela com Roquefort', 'Empanadita argentina gourmet', 'SNACKS', (SELECT id FROM menu), 7.00),
('Empanadita Argentina de Carne Caramelizada', 'Empanadita argentina de carne', 'SNACKS', (SELECT id FROM menu), 7.00),
('Pão Delícia de Azeitonas', 'Pão delícia com azeitonas', 'SNACKS', (SELECT id FROM menu), 5.00),
('Pão de Mandioquinha com Catupiry', 'Pão de mandioquinha com catupiry', 'SNACKS', (SELECT id FROM menu), 6.00),
('Enroladinho de Queijo com Linguicinha Toscana', 'Enroladinho gourmet', 'SNACKS', (SELECT id FROM menu), 7.00),
('Mini-Quiche Lorraine', 'Mini quiche lorraine', 'SNACKS', (SELECT id FROM menu), 6.00),
('Mini-Quiche de Palmito', 'Mini quiche de palmito', 'SNACKS', (SELECT id FROM menu), 6.00),
('Mini-Quiche de Alho Poró', 'Mini quiche de alho poró', 'SNACKS', (SELECT id FROM menu), 6.00),
('Croissant de Peito de Peru e Queijo', 'Croissant de peito de peru', 'SNACKS', (SELECT id FROM menu), 7.00),
('Pães de Queijo Recheado com Catupiry', 'Pão de queijo recheado', 'SNACKS', (SELECT id FROM menu), 5.00),
('Croissant de Presunto e Queijo', 'Croissant de presunto e queijo', 'SNACKS', (SELECT id FROM menu), 6.00),
('Coxinha Cremosa', 'Coxinha cremosa artesanal', 'SNACKS', (SELECT id FROM menu), 6.00),
('Vegan Toast de Zuchini com Homus e Nozes', 'Toast vegano de abobrinha', 'SNACKS', (SELECT id FROM menu), 7.00),
('Vegan Toast de Caponata com Pesto', 'Toast vegano de caponata', 'SNACKS', (SELECT id FROM menu), 7.00),
('Mini-Pão de Queijo de Mandioquinha', 'Mini pão de queijo vegano', 'SNACKS', (SELECT id FROM menu), 5.00),
('Mini-Pão de Queijo de Abóbora', 'Mini pão de queijo de abóbora', 'SNACKS', (SELECT id FROM menu), 5.00),
('Mini-Tostex de Presunto e Queijo', 'Mini tostex de presunto', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 6.00),
('Mini-Sírio com Mussarela de Búfala e Pesto', 'Mini sírio gourmet', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Mini-Bagel Lemon Pepper com Salame Hamburguês e Creme de Limão', 'Mini bagel especial', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 8.00),
('Paninni de Rosbife com Cebola Caramelizada', 'Paninni de rosbife', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 8.00),
('Mini-Bagel de Parmesão com Brie e Pesto de Tomate', 'Mini bagel de parmesão', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 8.00),
('Paninni Vegetariano de Azeitonas com Abobrinha e Berinjela Grelhada com Queijo e Manjericão', 'Paninni vegetariano', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 8.00),
('Mini-Tostex de Peito de Peru e Mussarela de Búfala', 'Mini tostex de peru', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Mini-Croque Monsieur de Presunto e Queijo', 'Mini croque monsieur', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Mini-Croque Monsieur de Cogumelos', 'Mini croque monsieur de cogumelos', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Mini-Sanduíche Egg Bacon', 'Mini sanduíche de ovo com bacon', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Queijo com Creme de Azeitonas, Queijo Branco e Pétala de Tomate Confit', 'Sanduíche gourmet de queijo', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 8.00),
('Alho Poró Caramelizado com Nuts', 'Sanduíche de alho poró', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Queijo Ementhal com Lombo Canadense e Cream Cheese com um toque de Limão', 'Sanduíche de lombo canadense', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 8.00),
('Creme de Tomate Seco com Abobrinha Confitada', 'Sanduíche de tomate seco', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Frango, Requeijão e Chia com Cenoura Laminada', 'Sanduíche de frango', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Peito de Peru com Queijo Meia Cura e Creme de Ervas', 'Sanduíche de peru', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Queijos Cremosos com Tomate Confitado, Azeite, Orégano', 'Sanduíche de queijos', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Salame Hamburguês com Queijo e Cream Cheese de Ervas', 'Sanduíche de salame', 'MINI-SANDUÍCHES', (SELECT id FROM menu), 7.00),
('Cenoura com Cobertura de Chocolate Trufado', 'Bolo de cenoura gourmet', 'BOLOS', (SELECT id FROM menu), 8.00),
('Maçã', 'Bolo de maçã caseiro', 'BOLOS', (SELECT id FROM menu), 6.00),
('Chocolate', 'Bolo de chocolate', 'BOLOS', (SELECT id FROM menu), 7.00),
('Cuca de Banana', 'Cuca de banana tradicional', 'BOLOS', (SELECT id FROM menu), 6.00),
('Cuca de Maçã', 'Cuca de maçã tradicional', 'BOLOS', (SELECT id FROM menu), 6.00),
('Fubá com Goiabada', 'Bolo de fubá com goiabada', 'BOLOS', (SELECT id FROM menu), 5.00),
('Cenoura com Brigadeiro', 'Bolo de cenoura com brigadeiro', 'BOLOS', (SELECT id FROM menu), 7.00),
('Muffin de Blueberry', 'Muffin de blueberry', 'BOLOS', (SELECT id FROM menu), 6.00),
('Muffin de Laranja', 'Muffin de laranja', 'BOLOS', (SELECT id FROM menu), 6.00),
('Brigadeiro', 'Brigadeiro tradicional', 'BOLOS', (SELECT id FROM menu), 4.00),
('Churros', 'Churros artesanal', 'BOLOS', (SELECT id FROM menu), 5.00),
('Milho', 'Bolo de milho', 'BOLOS', (SELECT id FROM menu), 5.00),
('Toalha Felpuda de Coco', 'Bolo toalha felpuda de coco', 'BOLOS', (SELECT id FROM menu), 5.00),
('Chocolate Vegano', 'Bolo de chocolate vegano', 'BOLOS', (SELECT id FROM menu), 7.00),
('Pudim de Leite', 'Pudim de leite tradicional', 'SOBREMESAS', (SELECT id FROM menu), 6.00),
('Pudim de Pistache', 'Pudim de pistache gourmet', 'SOBREMESAS', (SELECT id FROM menu), 8.00),
('Verrine de Brownie com Ganache e Coulis de Frutas Vermelhas', 'Verrine de brownie', 'SOBREMESAS', (SELECT id FROM menu), 9.00),
('Verrine Charge', 'Verrine charge (mousse de chocolate, caramelo salgado e amendoim)', 'SOBREMESAS', (SELECT id FROM menu), 9.00),
('Tapioca com Calda de Laranja e Leite de Coco, Mousse de Manga, Crumble e Iogurte', 'Tapioca gourmet', 'SOBREMESAS', (SELECT id FROM menu), 10.00),
('Brownie GLUTEN FREE com Açúcar de Coco e Ganache de Chocolate 70% com Laranja', 'Brownie gluten free', 'SOBREMESAS', (SELECT id FROM menu), 9.00),
('Tortinha de Brigadeiro', 'Tortinha de brigadeiro', 'SOBREMESAS', (SELECT id FROM menu), 5.00),
('Choux Cream de Pistache', 'Choux cream de pistache', 'SOBREMESAS', (SELECT id FROM menu), 7.00),
('Brownie de Chocolate', 'Brownie de chocolate', 'SOBREMESAS', (SELECT id FROM menu), 6.00),
('Carolina de Limão', 'Carolina de limão', 'SOBREMESAS', (SELECT id FROM menu), 6.00),
('Mini Pain Au Chocolat', 'Mini pain au chocolat', 'SOBREMESAS', (SELECT id FROM menu), 6.00),
('Tortinha de Limão', 'Tortinha de limão', 'SOBREMESAS', (SELECT id FROM menu), 5.00),
('Choux Cream de Creme de Baunilha', 'Choux cream de baunilha', 'SOBREMESAS', (SELECT id FROM menu), 7.00),
('Waffle com Nutella', 'Waffle com nutella', 'SOBREMESAS', (SELECT id FROM menu), 8.00),
('Waffle com Mel e Amêndoas', 'Waffle com mel e amêndoas', 'SOBREMESAS', (SELECT id FROM menu), 8.00),
('Mousse de Manga com Coco', 'Mousse de manga com coco', 'SOBREMESAS', (SELECT id FROM menu), 7.00),
('Canolli de Creme de Confeiteiro', 'Canolli de creme de confeiteiro', 'SOBREMESAS', (SELECT id FROM menu), 7.00),
('Canolli de Doce de Leite', 'Canolli de doce de leite', 'SOBREMESAS', (SELECT id FROM menu), 7.00),
('Canolli de Nutella', 'Canolli de nutella', 'SOBREMESAS', (SELECT id FROM menu), 7.00),
('Tortinha de Pêra', 'Tortinha de pêra vegana', 'SOBREMESAS', (SELECT id FROM menu), 6.00),
('Brownie de Chocolate com Nozes', 'Brownie de chocolate com nozes vegano', 'SOBREMESAS', (SELECT id FROM menu), 7.00),
('Frutas da Estação', 'Frutas da estação em cubos ou laminadas', 'FRUTAS DA ESTAÇÃO', (SELECT id FROM menu), 5.00);

-- ALMOÇO BUFFET -  PREMIUM
WITH menu AS (SELECT id FROM menus WHERE name = 'ALMOÇO BUFFET -  PREMIUM')
INSERT INTO dishes (name, description, category, menu_id, price) VALUES
('Água + Refri', 'Água e refrigerante', 'BEBIDAS NÃO ALCOÓLICAS', (SELECT id FROM menu), 6.00),
('2 Sucos', 'Dois sucos naturais', 'BEBIDAS NÃO ALCOÓLICAS', (SELECT id FROM menu), 8.00),
('Uva com Canela', 'Suco de uva com canela', 'SUCOS', (SELECT id FROM menu), 7.00),
('Abacaxi com Manjericão Orgânico', 'Suco de abacaxi com manjericão', 'SUCOS', (SELECT id FROM menu), 7.00),
('Limão com Hortelã e Gengibre', 'Suco de limão com hortelã e gengibre', 'SUCOS', (SELECT id FROM menu), 7.00),
('Maracujá com Abacaxi e Limão', 'Suco de maracujá com abacaxi e limão', 'SUCOS', (SELECT id FROM menu), 7.00),
('Morango com Melancia', 'Suco de morango com melancia', 'SUCOS', (SELECT id FROM menu), 7.00),
('Amora com Limão', 'Suco de amora com limão', 'SUCOS', (SELECT id FROM menu), 7.00),
('Lichia Lemonade', 'Limonada de lichia', 'SUCOS', (SELECT id FROM menu), 8.00),
('Caju', 'Suco natural de caju', 'SUCOS', (SELECT id FROM menu), 6.00),
('Laranja com Fruta da Época', 'Suco de laranja com fruta da época', 'SUCOS', (SELECT id FROM menu), 7.00),
('Abacaxi com Hortelã', 'Suco de abacaxi com hortelã', 'SUCOS', (SELECT id FROM menu), 7.00),
('Frutas Amarelas', 'Suco de frutas amarelas da estação', 'SUCOS', (SELECT id FROM menu), 7.00),
('Limão com Capim Santo', 'Suco de limão com capim santo', 'SUCOS', (SELECT id FROM menu), 7.00),
('Salada de Caponata com Straciatella', 'Salada de caponata gourmet', 'SALADAS', (SELECT id FROM menu), 12.00),
('Caprese Clássica com Tomate, Mussarela de Búfala e Folhas de Manjericão', 'Salada caprese clássica', 'SALADAS', (SELECT id FROM menu), 15.00),
('Salada de Lascas de Salmão com Frisée, Alface Roxa, Gergelim, Sour Cream de Wasabi e Teriyaki', 'Salada de salmão gourmet', 'SALADAS', (SELECT id FROM menu), 18.00),
('Ceviche de Pupunha com Zuchinni, Maçã Verde, Manjericão Roxo e Melaço', 'Ceviche de pupunha vegano', 'SALADAS', (SELECT id FROM menu), 14.00),
('Tartar Vegetariano de Tomate com Legumes, Queijo de Cabra e Azeite de Manjericão', 'Tartar vegetariano', 'SALADAS', (SELECT id FROM menu), 13.00),
('Rúcula com Espinafre, Grão de Bico com Páprica e Amêndoas', 'Salada de rúcula vegana', 'SALADAS', (SELECT id FROM menu), 11.00),
('Salada de Beterraba com Redução de Balsâmico, Hortelã, Chèvre e Nozes Caramelizadas', 'Salada de beterraba gourmet', 'SALADAS', (SELECT id FROM menu), 14.00),
('Carpaccio de Carne com Molho de Mostarda, Alcaparrones, Baby Rúcula e Lascas de Parmesão', 'Carpaccio de carne', 'SALADAS', (SELECT id FROM menu), 16.00),
('Mix de Folhas com Queijo Brie, Damasco, Nozes Caramelizadas e Mel Trufado', 'Mix de folhas gourmet', 'SALADAS', (SELECT id FROM menu), 15.00),
('Mix de Verdes com Radíchio, Tomate Sweet, Gorgonzola, Pêra e Nuts Caramelizados acompanha Dressing de Frutas Vermelhas', 'Mix de verdes premium', 'SALADAS', (SELECT id FROM menu), 16.00),
('Salada Julienne de Alface, Tomate, Palmito, Cenoura Ralada, Batata Palha e Parmesão Ralado, ao Molho de Mostarda e Azeite', 'Salada julienne', 'SALADAS', (SELECT id FROM menu), 12.00),
('Bife Ancho ao Molho Chimichurri', 'Bife ancho ao molho chimichurri', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 25.00),
('Beef Ribs ao Molho Bourbon', 'Beef ribs cozido por 12h em baixa temperatura', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 28.00),
('Beef Ribs ao Molho Demi-Glace', 'Beef ribs ao molho demi-glace', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 28.00),
('Bombom de Mignon com Fonduta de Gorgonzola', 'Bombom de mignon com gorgonzola', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 26.00),
('Bombom de Mignon ao Molho Mix de Mostardas', 'Bombom de mignon ao molho de mostardas', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 26.00),
('Bombom de Mignon ao Molho Demi-Glace', 'Bombom de mignon ao molho demi-glace', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 26.00),
('Bife de Tiras ao Molho Roti de Cogumelos', 'Bife de tiras ao molho de cogumelos', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 24.00),
('Chorizo ao Molho Chimichurri', 'Chorizo ao molho chimichurri', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 22.00),
('Ballotine de Frango Recheado com Queijo, Tomate Seco e Rúcula ao Molho Bechamel', 'Ballotine de frango recheado', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 20.00),
('Sobrecoxa de Frango ao Molho de Tangerina', 'Sobrecoxa de frango ao molho de tangerina', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 18.00),
('Arroz de Pato com Linguiça Artesanal e Batata Palha Crocante', 'Arroz de pato com linguiça', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 22.00),
('Peixe Branco Fresco Grelhado ao Bechamel de Limão Siciliano', 'Peixe branco grelhado', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 24.00),
('Peixe Branco Fresco ao Molho Champagne com Camarõezinhos', 'Peixe branco ao molho champagne', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 26.00),
('Lombo de Atum Selado com Gergelim, Teriyaki e Sour Cream de Wasabi', 'Lombo de atum selado', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 28.00),
('Salmão ao Molho Bechamel de Limão Siciliano', 'Salmão ao molho bechamel', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 30.00),
('Salmão Grelhado ao Molho de Frutas Vermelhas', 'Salmão grelhado ao molho de frutas', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 30.00),
('Polenta Cremosa finalizada no Azeite com Cogumelos Trufados e Legumes Braseados', 'Polenta cremosa vegana', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 18.00),
('Bobó Vegano de Abóbora com Cogumelos', 'Bobó vegano de abóbora', 'PRATOS PRINCIPAIS', (SELECT id FROM menu), 16.00),
('Ravioli Verde de Mussarela de Búfala ao Molho de Tomate Rústico e Parmesão Ralado', 'Ravioli verde de mussarela', 'MASSAS', (SELECT id FROM menu), 20.00),
('Agnolotti de Mussarela ao Molho de Tomates com Pesto e Fonduta de Parmesão', 'Agnolotti de mussarela', 'MASSAS', (SELECT id FROM menu), 20.00),
('Sorrentini de Ricota com Espinafre ao Molho Bechamel com Parmesão Ralado', 'Sorrentini de ricota', 'MASSAS', (SELECT id FROM menu), 18.00),
('Tortelli de Burrata com Limão Siciliano, ao Molho de Tomate e Manjericão', 'Tortelli de burrata', 'MASSAS', (SELECT id FROM menu), 22.00),
('Agnolotti de Brie com Emulsão de Manteiga e Azeite Trufado com Nuts Caramelizados', 'Agnolotti de brie', 'MASSAS', (SELECT id FROM menu), 24.00),
('Gnocchi de Mandioquinha ao Molho de Cogumelos Trufados', 'Gnocchi de mandioquinha', 'MASSAS', (SELECT id FROM menu), 18.00),
('Penne ao Molho de Tomate com Mussarela de Búfala, Azeitonas Laminadas, Tomate Seco, Manjericão e Lascas de Parmesão', 'Penne ao molho de tomate', 'MASSAS', (SELECT id FROM menu), 20.00),
('Nhoque de Abóbora Defumada com Molho de Tomate e Bacon Bites', 'Nhoque de abóbora vegano', 'MASSAS', (SELECT id FROM menu), 18.00),
('Batatas Rústicas', 'Batatas rústicas assadas', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 8.00),
('Risoto de Gorgonzola com Pera', 'Risoto de gorgonzola com pera', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 12.00),
('Musseline de Batata Trufada com Avelã', 'Musseline de batata trufada', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 10.00),
('Seleção de Legumes Orgânicos Sazonais Grelhados', 'Legumes orgânicos grelhados', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 9.00),
('Seleção de Mix de Cogumelos Regionais', 'Mix de cogumelos regionais', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 11.00),
('Arroz Vermelho com Aspargos', 'Arroz vermelho com aspargos', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 8.00),
('Arroz Negro com Pupunha', 'Arroz negro com pupunha', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 8.00),
('Torta Caprese de Tomates Assados', 'Torta caprese de tomates', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 9.00),
('Torta Ratatouille', 'Torta ratatouille', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 9.00),
('Mini-Medalhões de Pupunha Assada e Braseada', 'Mini-medalhões de pupunha', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 8.00),
('Couscous Marroquino com Brunoise de Legumes', 'Couscous marroquino', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 7.00),
('Gratin de Batatas', 'Gratin de batatas', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 8.00),
('Cenouras Baby Glaceadas', 'Cenouras baby glaceadas', 'ACOMPANHAMENTOS PREMIUM', (SELECT id FROM menu), 6.00),
('Pudim de Pistache', 'Pudim de pistache gourmet', 'SOBREMESAS', (SELECT id FROM menu), 10.00),
('Torta Creme Brulèe', 'Torta creme brulèe', 'SOBREMESAS', (SELECT id FROM menu), 12.00),
('Torta de Limão Azedinha', 'Torta de limão azedinha', 'SOBREMESAS', (SELECT id FROM menu), 10.00),
('Mil Folhas de Doce de Leite', 'Mil folhas de doce de leite', 'SOBREMESAS', (SELECT id FROM menu), 11.00),
('Canolli de Creme de Confeiteiro', 'Canolli de creme de confeiteiro', 'SOBREMESAS', (SELECT id FROM menu), 9.00),
('Canolli de Doce de Leite', 'Canolli de doce de leite', 'SOBREMESAS', (SELECT id FROM menu), 9.00),
('Entremet de Pão de Mel', 'Entremet de pão de mel', 'SOBREMESAS', (SELECT id FROM menu), 10.00),
('Cheesecake de Frutas Vermelhas', 'Cheesecake de frutas vermelhas', 'SOBREMESAS', (SELECT id FROM menu), 11.00),
('Entremet de Pistache', 'Entremet de pistache', 'SOBREMESAS', (SELECT id FROM menu), 12.00),
('Verrine de Torta de Limão Desconstruída', 'Verrine de torta de limão', 'SOBREMESAS', (SELECT id FROM menu), 11.00),
('Brownie de Chocolate com Ganache e Coulis de Frutas Vermelhas', 'Brownie de chocolate gourmet', 'SOBREMESAS', (SELECT id FROM menu), 10.00),
('Pavlova de Frutas Tropicais', 'Pavlova de frutas tropicais', 'SOBREMESAS', (SELECT id FROM menu), 12.00),
('Tiramissú VEGAN', 'Tiramissú vegano', 'SOBREMESAS', (SELECT id FROM menu), 10.00),
('Frutas da Estação', 'Frutas da estação laminada ou cubos', 'FRUTAS DA ESTAÇÃO', (SELECT id FROM menu), 6.00);

-- Criar relacionamentos entre menus e pratos
INSERT INTO menu_dishes (menu_id, dish_id)
SELECT m.id, d.id
FROM menus m
JOIN dishes d ON d.menu_id = m.id
ON CONFLICT DO NOTHING; 